### ISSUE TITLE
COMPANY vs ORGANIZATION Variables. 

### ISSUE THREAD

**Issue by sn3ak** [christian-moerz/openvas#1]
I believe there is a mistake in the script. It appears you call COMPANY=Company in the declarations, but later you call it ORGANIZATION.

https://github.com/christian-moerz/openvas/blob/2769b03e2eefac9db08059025f577038d5035d70/openvas-install.sh#L8
https://github.com/christian-moerz/openvas/blob/2769b03e2eefac9db08059025f577038d5035d70/openvas-install.sh#L192

Regards

**Comment by christian-moerz** [comment]
Thanks for the feedback!
