### ISSUE TITLE
Vendor Supplied Patches for pcre 2 compatibility 

### ISSUE THREAD

**Issue by sn3ak** [christian-moerz/openvas#2]
FYI these patches fix the user issue and apparently other things as well.

https://github.com/greenbone/gvmd/commit/9a19649ff9aaf108b91baefd69699c1f325cd34d
https://github.com/greenbone/gvmd/pull/1867/commits/912350f7c40e47b24c121d7d1a27a2ec5bcd9754

**Comment by sn3ak** [comment]
There's also a patch for gsad:
https://github.com/greenbone/gsad/commit/f96d1d75056cae6e1f696fffb36b5250e8a5816b

**Comment by christian-moerz** [comment]
Merged those patches and will test whether it works with current ports. If it does, I'll post patches for upstream / port, because this should really be fixed there. Thanks for looking those up and posting them!

**Comment by christian-moerz** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=267429; gvmd patches appear to not work or not be necessary - scan configuration could no longer be added, once those patches were applied. I've updated the script to include gsad patches only and filed linked upstream patch.
Thanks again for the great feedback!
