### ISSUE TITLE
User creation failed

### ISSUE THREAD

**Issue by felipebsd** [christian-moerz/openvas#4]
sent 677 bytes  received 86,970,396 bytes  971,743.83 bytes/sec
total size is 86,932,252  speedup is 1.00
Creating GVM admin user : qwe123
**Failed to create user: Invalid characters in user name**

\# uname -a
FreeBSD template.titaniotecnologia.corp 13.1-RELEASE FreeBSD 13.1-RELEASE releng/13.1-n250148-fc952ac2212 GENERIC amd64

**Comment by christian-moerz** [comment]
You are affected by an upstream issue; I'll post a patch in a minute, but it might break in future ports updates. For the moment, this should work with ports branch 2022Q4.
I.e. to get working ports branch use
git clone -b 2022Q4 --depth 1 https://git.freebsd.org/ports.git /usr/ports

**Comment by christian-moerz** [comment]
Should be fixed with release 2022_12.1
