### ISSUE TITLE
fails attempt at installing samba412

### ISSUE THREAD

**Issue by sremick** [christian-moerz/openvas#5]
Trying this on a FreeBSD13 VM. I get past the account password creation, then get this:

`This installation is automated and does not require any further user
interaction but it will take a while to complete...

PREREQS
Installing prerequisite utilities.
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
pkg: No packages available to install matching 'samba412' have been found in the repositories
`
I already have samba413 installed. Seems hard-coded for samba412 which doesn't exist anymore...?

**Comment by christian-moerz** [comment]
thanks to @gnomii , this was just fixed. Just realized I missed your issue. Glad, it's finally fixed.
